server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    username: madaffrager
    password: password
    url: jdbc:postgresql://localhost:5433/customer

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
